apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-httpd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/michi-1221/workshop-gitops-sample.git
    targetRevision: main
    path: manifests/httpd
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
